[env:generic_rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
upload_flags = -f
build_flags = -DRT_RP2040

[env:pico_rp2040]
extends = env:generic_rp2040
build_flags = ${env:generic_rp2040.build_flags} -DRT_PICO

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
build_flags =  -DPIO_FRAMEWORK_ARDUINO_ENABLE_CDC
               -DUSBCON
               -DRT_BLUEPILL

[env:bluepill_f103c8_boot8k]
extends = env:bluepill_f103c8
; 8kib bootloader
board_upload.offset_address = 0x08002000
board_build.flash_offset    = 0x2000
upload_protocol = dfu
